#ifndef __ASSEMBLER_H
#define __ASSEMBLER_H

#define NUM_OF_FUNC 27
#define NUM_OF_DIR 6
#define NUM_OF_REG 32
#define GAP_BETWEEN_LIST_OPCODE 2
#define MAX_LINE_LENGTH 80
#define FILE_EXT ".as"
#define CODE_MEM_SIZE 10000
#define INITIAL_MEM_ADDRESS 100
#define INSTRUCTION_SIZE 4

#endif